### ISSUE TITLE
XMLRPC FAULT [401]

### ISSUE THREAD

**Issue by Vxer-Lee** [xiajingren/EasyBlogImageForTypora#5]
今天博客园好像突然得用令牌来登陆了，测试了好久发现用户名和登陆密码已经失效了，会出现如下提示。
![image](https://user-images.githubusercontent.com/27657137/174584020-333294cb-4f84-4723-9bea-48ec7847f37b.png)
可以在这个地方创建令牌
![image](https://user-images.githubusercontent.com/27657137/174584410-41c50dff-6d37-4456-ae37-1846d5ee43bf.png)

感觉上传速度，明显没有以前快了。。。

**Comment by BNTang** [comment]
创建了令牌但是在typora上传还是报错

**Comment by BNTang** [comment]
![image](https://user-images.githubusercontent.com/78400939/174821507-88a86d94-8c73-4716-8ee7-bcf56cea4012.png)

**Comment by BNTang** [comment]
![image](https://user-images.githubusercontent.com/78400939/174821507-88a86d94-8c73-4716-8ee7-bcf56cea4012.png)

**Comment by BNTang** [comment]
![image](https://user-images.githubusercontent.com/78400939/174822328-1be2071f-9b27-4677-af14-fe5c78046919.png)

**Comment by Vxer-Lee** [comment]
> ![image](https://user-images.githubusercontent.com/78400939/174822328-1be2071f-9b27-4677-af14-fe5c78046919.png)

你怎么创建的，我的是可以，现在都在正常使用，而且速度好像变快了。

**Comment by BNTang** [comment]
这就很神奇了我就是安装作者的文档，配置了博客信息，然后在typora 当中把需要上传的图片ctrl+v它就报错了

**Comment by BNTang** [comment]
> > ![image](https://user-images.githubusercontent.com/78400939/174822328-1be2071f-9b27-4677-af14-fe5c78046919.png)
> 
> 你怎么创建的，我的是可以，现在都在正常使用，而且速度好像变快了。
![image](https://user-images.githubusercontent.com/78400939/175756315-2d84a765-3833-43b6-9a99-30ac8cda6c27.png)

**Comment by asdfdaafd** [comment]
我也不可以正常使用了，哪位大神帮帮§(*￣▽￣*)§

**Comment by BNTang** [comment]
> 我也不可以正常使用了，哪位大神帮帮§(_￣▽￣_)§

- 可以参考一下这个：https://www.cnblogs.com/BNTang/articles/16173301.html
- 我目前先用官方提供的，等这个问题查清楚之前在换回来

**Comment by xiajingren** [comment]
可以用啊，去博客园后台创建下令牌，重新配置下EasyBlogImageForTypora，密码输入你创建的令牌，就行了。
